version: '3.7'

services:
  postgresdb:
    image: postgres:latest
    restart: always
    volumes:
      - verilerim:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345

  app:
    image: docker_deneme
    build: ./
    container_name: app
    depends_on:
      - postgresdb
    ports:
      - "8081:8081"

volumes:
  verilerim:





